# Generated by Django 2.0 on 2017-12-11 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_request_id', models.IntegerField()),
                ('update_dict', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
