# Generated by Django 2.0 on 2018-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateresponse',
            name='class_info_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updateresponse',
            name='class_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
