# Generated by Django 2.0 on 2018-05-15 13:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_info_id', models.IntegerField(blank=True, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=36, null=True)),
                ('invoice_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
