# Generated by Django 2.0 on 2018-05-31 22:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalinvoice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypalinvoice',
            name='success',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paypalinvoice',
            name='invoice_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
