# Generated by Django 2.0 on 2017-12-04 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone Number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('country', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('open', 'Open Time')], default='open', max_length=8)),
                ('preferred_im', models.CharField(choices=[('whatsapp', 'WhatsAPP'), ('telegram', 'Telegram'), ('skype', 'Skype'), ('hangouts', 'Hangouts')], default='whatsapp', max_length=16)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_on', models.DateTimeField(editable=False)),
            ],
        ),
    ]
