# Generated by Django 2.0 on 2018-03-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvt_send_timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.NullBooleanField(default=True)),
                ('class_resquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing_page.ClassRequest')),
            ],
        ),
    ]
