# Generated by Django 2.0 on 2018-03-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_classinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='teacher',
            field=models.CharField(default='', max_length=128),
        ),
    ]
