# Generated by Django 2.0 on 2018-03-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_classinfo_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classinfo',
            old_name='class_resquest',
            new_name='class_request',
        ),
        migrations.AddField(
            model_name='classinfo',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='q1_sent',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
