# Generated by Django 2.0 on 2018-04-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20180331_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='proof',
            field=models.ImageField(blank=True, null=True, upload_to='proof/'),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='q2_sent',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='classinfo',
            name='reason_why',
            field=models.TextField(blank=True, null=True),
        ),
    ]
