# Generated by Django 2.0 on 2018-04-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20180406_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinfo',
            name='q2_sent_msgid',
            field=models.IntegerField(default=0),
        ),
    ]
