# Generated by Django 2.0 on 2018-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_classinfo_q2_sent_msgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='proof',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='proof/'),
        ),
    ]
